### PR TITLE
Version 0.5.0

### PR DESCRIPTION
**Pull request by m-ou-se**

### CODE REVIEW

**Comment by m-ou-se** [comment]
What do we want to do with existing code that uses `#![context = &c]`? Right now, the code in the PR will just give that line to Python, which will see it as a comment because of the `#`.

Should we panic, give a warning, or still support this syntax?

**Comment by de-vri-es** [comment]
I think we should give an error if we find it. Not very nice if it is silently ignored.

**Comment by m-ou-se** [comment]
It now gives this error:

screenshot

**Comment by de-vri-es** [comment]
Cool. Might be nice to highlight the entire attribute for the error, but this is certainly good enough.

**Pull request merged**
